# yaml-language-server: $schema=https://www.rubyschema.org/rubocop.json

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - lib/bulma_phlex/**/*.rb

Metrics/AbcSize:
  Exclude:
    - lib/bulma_phlex/pagination.rb
    - lib/bulma_phlex/tabs.rb
Metrics/BlockLength:
  Exclude:
    - lib/bulma_phlex/pagination.rb
    - lib/bulma_phlex/tabs.rb
Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
Metrics/CyclomaticComplexity:
  Exclude:
    - lib/bulma_phlex/pagination.rb
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  CountKeywordArgs: false
Metrics/PerceivedComplexity:
  Exclude:
    - lib/bulma_phlex/pagination.rb

Naming/FileName:
  Exclude:
    - lib/bulma-phlex.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
